config/routes.rb
Print3d::Application.routes.draw do

  resources :articles
  resources :models

  get "omniauth_callbacks/facebook"
  get "omniauth_callbacks/vkontakte"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users, :only => [:index, :show, :edit, :update, :destroy] do
    member do
      get "/billing", to: "users#billing", as: :billing
    end
  end

  get "/index.html", to: "static_pages#index"
  get "/o-proekte.html", to: "static_pages#about"
  get "/kontakti.html", to: "static_pages#contacts"

  root :to => 'static_pages#index'
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :count_see, :name, :picture, :text
end

app/models/model.rb
class Model < ActiveRecord::Base
  attr_accessible :count_down, :count_see, :file, :image, :name, :pay, :text, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :avatar, :name, :pocket, :sent
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  # GET /models
  # GET /models.json
  def index
    @models = Model.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @models }
    end
  end

  # GET /models/1
  # GET /models/1.json
  def show
    @model = Model.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @model }
    end
  end

  # GET /models/new
  # GET /models/new.json
  def new
    @model = Model.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @model }
    end
  end

  # GET /models/1/edit
  def edit
    @model = Model.find(params[:id])
  end

  # POST /models
  # POST /models.json
  def create
    @model = Model.new(params[:model])

    respond_to do |format|
      if @model.save
        format.html { redirect_to @model, notice: 'Model was successfully created.' }
        format.json { render json: @model, status: :created, location: @model }
      else
        format.html { render action: "new" }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /models/1
  # PUT /models/1.json
  def update
    @model = Model.find(params[:id])

    respond_to do |format|
      if @model.update_attributes(params[:model])
        format.html { redirect_to @model, notice: 'Model was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /models/1
  # DELETE /models/1.json
  def destroy
    @model = Model.find(params[:id])
    @model.destroy

    respond_to do |format|
      format.html { redirect_to models_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def about
  end

  def contacts
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def vkontakte
    @user = User.find_for_vkontakte_oauth(request.env["omniauth.auth"])
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Vkontakte"
      sign_in_and_redirect @user, :event => :authentication
    else
      flash[:notice] = "authentication error"
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :set_user, only: [:show, :edit, :update, :billing, :destroy]

  respond_to :html

  def index
    @users = User.all
    respond_with(@users)
  end

  def billing
    respond_with(@user)
  end

  def show
    respond_with(@user)
  end

  def new
    @user = User.new
    respond_with(@user)
  end

  def edit
  end

  def create
    @user = User.new(params[:user])
    @user.save
    respond_with(@user)
  end

  def update
    @user.update_attributes(params[:user])
    respond_with(@user)
  end

  def destroy
    @user.destroy
    respond_with(@user)
  end

  private
    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
# encoding: UTF-8

module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "3d модели"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end


  def is_active(action)       
    params[:action] == action ? "active" : nil        
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :count_see %><br />
    <%= f.number_field :count_see %>
  </div>
  <div class="field">
    <%= f.label :picture %><br />
    <%= f.text_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="keywords" content="3d модели, 3d принтер, 3d, печать на 3d принтере, .STL, .SCAD, 3d модели скачать, бесплатные 3d модели, 3d модель человека, форматы 3d моделей" />
  <meta name="description" content="3d модели для 3D принтеров. Бесплатные и платные модели с регистрацией." />
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" /> 

</head>
<body>

	<%= render 'static_pages/header' %>
	<%= yield %>
	<%= render 'static_pages/footer' %>

</body>
</html>

app/views/models/_form.html.erb
<%= form_for(@model) do |f| %>
  <% if @model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@model.errors.count, "error") %> prohibited this model from being saved:</h2>

      <ul>
      <% @model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label :pay %><br />
    <%= f.check_box :pay %>
  </div>
  <div class="field">
    <%= f.label :file %><br />
    <%= f.text_field :file %>
  </div>
  <div class="field">
    <%= f.label :count_see %><br />
    <%= f.number_field :count_see %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :count_down %><br />
    <%= f.number_field :count_down %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/models/edit.html.erb
<h1>Editing model</h1>

<%= render 'form' %>

<%= link_to 'Show', @model %> |
<%= link_to 'Back', models_path %>

app/views/models/new.html.erb
<h1>New model</h1>

<%= render 'form' %>

<%= link_to 'Back', models_path %>

app/views/models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @model.name %>
</p>

<p>
  <b>Text:</b>
  <%= @model.text %>
</p>

<p>
  <b>Pay:</b>
  <%= @model.pay %>
</p>

<p>
  <b>File:</b>
  <%= @model.file %>
</p>

<p>
  <b>Count see:</b>
  <%= @model.count_see %>
</p>

<p>
  <b>User:</b>
  <%= @model.user_id %>
</p>

<p>
  <b>Count down:</b>
  <%= @model.count_down %>
</p>

<p>
  <b>Image:</b>
  <%= @model.image %>
</p>


<%= link_to 'Edit', edit_model_path(@model) %> |
<%= link_to 'Back', models_path %>

app/views/static_pages/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-md-6 col-lg-6">
        <h2>Подпишитесь на новости сервиса</h2>
        <p class="mt-0 mb-30">Вы будете получать новости проекта, сообщения об акциях сервиса</p>
        <!-- Begin MailChimp Signup Form -->
        <div id="mc_embed_signup" class="row mb-15">
          <form action="http://autodesk.us7.list-manage.com/subscribe/post?u=229fda9ef668fad2907e96057&amp;id=661d508cb6" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
            <div class="input-group input-group-lg mb-30 col-md-10 col-lg-10">
              <input type="email" value="" name="EMAIL" class="email form-control" placeholder="Введите свой email" id="mce-EMAIL" required>
              <span class="input-group-btn">
              <button type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="btn btn-default">Отправить</button>
              </span> </div>
          </form>
        </div>
        <!--End mc_embed_signup-->

      </div>
      <!-- /.col-lg-6 -->
      <div class="col-sm-6 col-md-6 col-lg-6">
        <h2>3D Models в социальных сетях</h2>
        <p class="mt-0">Последние новости и обсуждения. Мы интерактивны!</p>
        <p><a href="http://www.facebook.com/Autodesk123D" target="_blank" class="mr-10"><img src="http://cdn.123dapp.com/wp/wp-content/uploads/2014/02/facebook.png" alt="Visit 123D on Facebook" width="60" height="60"></a> <a href="http://www.twitter.com/Autodesk123D" target="_blank" class="mr-10"><img src="http://cdn.123dapp.com/wp/wp-content/uploads/2014/02/twitter.png" alt="Visit 123D on Twitter" width="60" height="60"></a> <a href="http://www.youtube.com/Autodesk123D" target="_blank" class="mr-10"><img src="http://cdn.123dapp.com/wp/wp-content/uploads/2014/02/youtube.png" alt="Visit 123D on YouTube" width="60" height="60"></a> <a href="http://www.pinterest.com/Autodesk123D" target="_blank"><img src="http://cdn.123dapp.com/wp/wp-content/uploads/2014/02/pinterest.png" alt="Visit 123D on Pinterest" width="60" height="60"></a></p>
      </div>
      <!-- /.col-lg-6 -->
    </div>
    <!-- /.row -->
  </div>
</footer>
<div class="container info mt-30 mb-30 pb-30 pt-30">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-6">
      <p><a href="http://autodesk.com" target="_blank"><img alt="Go to Autodesk.com" src="http://cdn.123dapp.com/wp/wp-content/uploads/2014/02/123D_logo_footer.png"></a></p>
      <p>3D проектирование - относительно новое направление. С появлением доступных 3D принтеров у множества людей появилась возможность в домашних условиях или в офисе легко и быстро создать масштабную модель.</p>
      <p>&copy; 2015 ООО "Инфоком-НН". Все права защищены.</p>
      <ul class="list-inline list-unstyled">
        <li><a href="#" target="_blank">Пользовательское соглашение</a></li>
        <li><a href="#" target="_blank">Карта сайта</a></li>
      </ul>
    </div>
    <div class="col-xs-12 col-sm-4 col-md-2">
      <h4>Меню</h4>
      <ul class="list-unstyled">
        <li><a href="/design">123D Design</a></li>
        <li><a href="/make">123D Make</a></li>
        <li><a href="/sculptplus">123D Sculpt+</a> <span class="label label-success">New</span></li>
        <li><a href="/catch">123D Catch</a></li>
        <li><a href="/circuits">123D Circuits</a></li>
        <li><a href="http://www.tinkercad.com" target="_blank">Tinkercad</a></li>
        <li><a href="/meshmixer">Meshmixer</a></li>
        <li><a href="/sandbox#section-shapeshifter">Project Shapeshifter</a></li>
      </ul>
    </div>

  </div>
</div>

<script>
    $('#NavBar').affix({
        offset: {
            top: 100
        }
    });

</script>

app/views/static_pages/_header.html.erb
<link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700|Open+Sans:400,600,700|Shadows+Into+Light' rel='stylesheet' type='text/css'>
<link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.css" rel="stylesheet">

<!-- Scripts are placed here -->
<script src="http://www.123dapp.com/builds/base.master.libs.script-e9b4b029040427794e0e2dd514d822d2.js"></script>

<div id="NavBar" class="navbar-wrap">
  <nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">
        <img src="http://cdn.123dapp.com/wp/wp-content/uploads/2014/05/logo-123d.png" alt="Autodesk 123D" alt="Autodesk 123D" class="img-responsive" />
      </a>
    </div>
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav">
        <li class="first has-subnav">
          <a href="/">
            Главная
          </a>
        </li>
        <li class="has-subnav">
          <%= link_to "Каталог 3D моделей", models_path %>
        </li>
        <li>
          <%= link_to "Блог", articles_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
            <li class="MenuGoPremium">
              <a href="/gopremium" id="track-header-gopremium">
                Безлимитный доступ
              </a>
            </li>

            <li class="has-subnav navitem-account MenuMember" ">
            <%= link_to "<img class='avatar MenuAvatarImage' alt='' src='/images/default_avatar.png'/>
              <span class='navitem-messages'> Аккаунт</span>".html_safe, user_path(current_user), :class => "avatar-link MenuAvatar MenuAccountLink", :rel => "nofollow" %>
            <div class="dropdown-menu dropdown-menu-account">
              <ul class="sub-nav">
                <li>
                  <%= link_to "<span class='glyphicon glyphicon-user'></span> Мой профайл".html_safe, user_path(current_user), :class => "MenuAccountLink", :rel => "nofollow" %>
                </li>
                <li>
                  <a class="MenuAccountLink" href="/MyCorner/@member-info@/downloads" rel="nofollow">
                    <span class="glyphicon glyphicon-bullhorn"></span>
                    Скаченный модели
                  </a>
                </li>
                <li class="divider"></li>
                <li class="MenuGoPremium">
                  <a href="/gopremium" id="track-header-gopremium">
                    Безлимитный доступ
                  </a>
                </li>
                <li>
                  <%= link_to "Выйти", destroy_user_session_path, :method => :delete, :class => "MenuLogout", :id => "logout", :rel => "nofollow" %>
                </li>
              </ul>
            </div>
            </li>



        <% else %>
            <li>
              <%= link_to "Зарегистрироваться", new_user_registration_path, :class => "MenuGuest", :rel => "nofollow" %>
            </li>
            <li>
              <%= link_to "Войти", new_user_session_path, :class => "MenuGuest MenuLogin", :rel => "nofollow" %>
            </li>
        <% end %>

      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </nav>
  <!-- /Main nav -->
</div>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contacts.html.erb
<h1>StaticPages#contacts</h1>
<p>Find me in app/views/static_pages/contacts.html.erb</p>

app/views/static_pages/index.html.erb
  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <img src="http://cdn.123dapp.com/wp/wp-content/uploads/2015/01/introducing-123d-sculpt-plus.jpg" alt="Introducing 123D Sculpt+" />
      <div class="carousel-caption" style="left: 50%">
        <h2 style="text-shadow: 1px 1px 25px #000; color: #FFF;">Каталог моделей 3D</h2>
        <p class="lead hidden-xs hidden-sm">Найти 3D модель для принтера</p>
        <p><%= link_to "Найти 3D модель", models_path, :class => "btn btn-primary btn-lg" %></p>
      </div>
    </div>
  </div>

<section class="section section-gray">
  <div class="container">
    <div class="row">
      <!-- Content -->
      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 pr-50">
        <h3 class="mt-0">Бесплатно скачивайте 3D модели для 3D принтера!</h3>
        <p>Ищите 3D модели? В нашем каталоге вы можете найти тысячи моделей для 3D принтеров в формате .stl</p>
        <p>У нас есть платные и бесплатные модели. Стоимость платных составляет всего 30 рублей за скачивание!</p>
        <p><a href="/create" class="btn btn-default">Найти модель</a> <a href="/gallery" class="btn btn-default">Browse 3D Models</a>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 ">
        <div class="row">
          <div class="col-xs-12 col-md-12 col-lg-12">
            <ul class="media-list">
              <li class="media">
                <a class="pull-left" href="/catch">
                  <img src="http://cdn.123dapp.com/wp/wp-content/uploads/2014/04/productIcon_Catch_48x48.png" width="80" heilt="80"/>
                </a>
                <div class="media-body">
                  <h4 class="media-heading"><a href="/catch">123D Catch</a></h4>
                  <span>Generate 3D models from photos ываы аыва уц апвап п вапвыкпе вапикп ап кп вяпвпк пвпе аып р вапрывп ареып парквер па</span> </div>
              </li>
              <li class="media"><a class="pull-left" href="/circuits">
                <img src="http://cdn.123dapp.com/wp/wp-content/uploads/2014/04/productIcon_Circuits_48x48.png" width="80" heilt="80" alt=""/> </a>
                <div class="media-body">
                  <h4 class="media-heading"><a href="/circuits">123D Circuits</a></h4>
                  <span>Design your next electronic project ываы аыва уц апвап п вапвыкпе вапикп ап кп вяпвпк пвпе аып р вапрывп ареып парквер па</span> </div>
              </li>
              <li class="media"><a class="pull-left" href="/design"> <img src="http://cdn.123dapp.com/wp/wp-content/uploads/2014/04/productIcon_Design_48x48.png" width="80" heilt="80" alt=""/> </a>
                <div class="media-body">
                  <h4 class="media-heading"><a href="/design">123D Design</a></h4>
                  <span>Easy 3D modeling for Web, Mac, and PC ываы аыва уц апвап п вапвыкпе вапикп ап кп вяпвпк пвпе аып р вапрывп ареып парквер па</span> </div>
              </li>
              <li class="media"><a class="pull-left" href="/make"> <img src="http://cdn.123dapp.com/wp/wp-content/uploads/2014/04/productIcon_Make_48x48.png" width="80" height="80"  alt=""/> </a>
                <div class="media-body">
                  <h4 class="media-heading"><a href="/make">123D Make</a></h4>
                  <span>Unique 3D models from 2D slices ываы аыва уц апвап п вапвыкпе вапикп ап кп вяпвпк пвпе аып р вапрывп ареып парквер па </span></div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/_profile_start.html.erb
<div class="container page-profile mt-25">
  <div class="row">
    <div class="col-xs-12 col-sm-5 col-md-4 col-lg-3">
      <div class="list-group">
        <div class="user-info"><img class="img-responsive" src="http://www.123dapp.com/Images/v23/Member/default_avatar.png">
          <h2><%= @user.name %></h2>
          <p class="list-group-item-text">                                               </p>
        </div>
        <a class="list-group-item active" href="/MyCorner/KirillBelov 234-23465794/summary">
          <h4 class="list-group-item-heading"><span class="glyphicon glyphicon-user"></span> Мой профайл </h4>
        </a>
        <a class="list-group-item " href="/MyCorner/KirillBelov 234-23465794/models">
          <h4 class="list-group-item-heading"><span class="glyphicon glyphicon-th"></span> Скаченный модели </h4>
        </a>
      </div>
    </div>
    <div class="col-xs-12 col-sm-7 col-md-8 col-lg-9">
      <div class="panel panel-default">

app/views/users/billing.html.erb
<%= render "profile_start" %>

<%= render "/users/profile/top_menu" %>

<div class="panel-body">
  <div class="row">
    <div class="col-lg-12">
      <dl class="dl-horizontal">
        <dt>Membership level:</dt>
        <dd>
          <strong>Free member</strong>

          <a href="/gopremium">Upgrade to Premium now</a>
          |
          <a href="http://www.123dapp.com/Subscriptions/UpgradeAccount.cfm">Why upgrade?</a>
        </dd>
      </dl>
      <dl class="dl-horizontal">
        <dt>Next billing date:</dt>
        <dd>None
        </dd>
      </dl>
      <dl class="dl-horizontal">
        <dt>Recent payments:</dt>
        <dd>You have no recent payments.</dd>
      </dl>
      <!--            <hr>
      <div class="text-right"><a data-toggle="modal" href="#myModal3">Delete My Account</a></div>-->
    </div>
  </div>
</div>

</div>
</div>
</div>
</div>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Avatar</th>
    <th>Pocket</th>
    <th>Sent</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.avatar %></td>
    <td><%= user.pocket %></td>
    <td><%= user.sent %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/letters.html.erb
<%= render "profile_start" %>

<!-- Content navigation -->
<div class="panel-heading pb-0">
  <ul class="nav nav-tabs">
    <li><%= link_to "Профайл", user_path(current_user) %></li>
    <li ><%= link_to "Изменить профайл", edit_user_path(current_user) %></li>
    <li class="active"><%= link_to "Ваши подписки", "/letters" %></li>
    <li ><a href="billing">Безлимитный доступ</a></li>
  </ul>
</div>
<!-- Content navigation -->

<div class="panel-body">
  <div class="row">
    <div class="col-lg-12">
      <h3 class="mb-30">Email preferences</h3>
      <p>When do you want to receive notifications of  <strong>messages, follows, comments</strong>, etc?</p>
      <div class="form-group">
        <div class="btn-group notification">
          <button class="btn btn-default preferenceButton " type="button" id="not_1">Immediately</button>
          <button class="btn btn-default preferenceButton " type="button" id="not_2">Hourly</button>
          <button class="btn btn-default preferenceButton active" type="button" id="not_3">Daily</button>
          <button class="btn btn-default preferenceButton " type="button" id="not_4">Weekly</button>
          <button class="btn btn-default preferenceButton " type="button" id="not_0">Never</button>
        </div>
      </div>
      <p>When should we send the <strong>Autodesk 123D Newsletter</strong>?</p>
      <div class="form-group">
        <div class="btn-group adsk123d">
          <button class="btn btn-default preferenceButton " type="button" id="adsk123d_1">Occasionally</button>
          <button class="btn btn-default preferenceButton active" type="button" id="adsk123d_0">Never</button>
        </div>
      </div>
      <p>When should we send the <strong>Autodesk 123D Artist Newsletter</strong>?</p>
      <div class="form-group">
        <div class="btn-group adsk123dArtist">
          <button class="btn btn-default preferenceButton " type="button" id="adsk123dArtist_1">Occasionally</button>
          <button class="btn btn-default preferenceButton active" type="button" id="adsk123dArtist_0">Never</button>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <hr>
      <button class="btn btn-primary btn-lg updatePreferences" type="submit">Update changes</button>
    </div>
  </div>
  <form action="preferences" method="post" id="preferenceForm">
    <input type="hidden" name="notification" id="notification" value="3">
    <input type="hidden" name="adsk123d" id="adsk123d" value="0">
    <input type="hidden" name="adsk123dArtist" id="adsk123dArtist" value="0">
  </form>
</div>

</div>
</div>
</div>
</div>

app/views/users/profile/_top_menu.html.erb
<!-- Content navigation -->
<div class="panel-heading pb-0">
  <ul class="nav nav-tabs">
    <li><%= link_to "Профайл", user_path(current_user) %></li>
    <li><%= link_to "Изменить профайл", edit_user_path(current_user) %></li>
    <li><%= link_to "Безлимитный доступ", billing_user_path(current_user) %></li>
  </ul>
</div>
<!-- Content navigation -->